#!/usr/bin/env python3
"""Generate device.yaml configuration file for pressure test."""
import argparse
import json
import sys
import os

def main():
    parser = argparse.ArgumentParser(description='Generate device.yaml')
    parser.add_argument('--output', required=True, help='Output YAML file path')
    parser.add_argument('--common', required=True, help='JSON string of common config fields')
    parser.add_argument('--extra', default='{}', help='JSON string of scenario-specific config fields')
    args = parser.parse_args()

    common = json.loads(args.common)
    extra = json.loads(args.extra)

    # Merge: extra fields first (scenario-specific), then common fields
    all_config = {}
    all_config.update(extra)
    all_config.update(common)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    with open(args.output, 'w', encoding='utf-8') as f:
        # Write header comment
        f.write('# ============================================\n')
        f.write('# Pressure Test Configuration\n')
        f.write('# Auto-generated by pressure-test skill\n')
        f.write('# ============================================\n\n')

        # Write scenario-specific fields first
        if extra:
            f.write('# --- Scenario-specific configuration ---\n')
            for key, value in extra.items():
                f.write(format_yaml_value(key, value))
            f.write('\n')

        # Write common fields
        f.write('# --- Common configuration ---\n')
        for key, value in common.items():
            f.write(format_yaml_value(key, value))

    print(f'YAML config generated: {args.output}')


def format_yaml_value(key, value, indent=0):
    """Format a key-value pair as YAML."""
    prefix = '    ' * indent
    if isinstance(value, bool):
        return f'{prefix}{key}: {str(value)}\n'
    elif isinstance(value, (int, float)):
        return f'{prefix}{key}: {value}\n'
    elif isinstance(value, str):
        # Quote strings that might be misinterpreted
        if value.lower() in ('true', 'false', 'null', 'yes', 'no', '') or value.isdigit():
            return f'{prefix}{key}: "{value}"\n'
        return f'{prefix}{key}: "{value}"\n'
    elif isinstance(value, list):
        result = f'{prefix}{key}:\n'
        for item in value:
            if isinstance(item, list):
                result += f'{prefix}    - {json.dumps(item, ensure_ascii=False)}\n'
            else:
                result += f'{prefix}    - {json.dumps(item, ensure_ascii=False)}\n'
        return result
    elif isinstance(value, dict):
        result = f'{prefix}{key}:\n'
        for k, v in value.items():
            result += format_yaml_value(k, v, indent + 1)
        return result
    else:
        return f'{prefix}{key}: {json.dumps(value, ensure_ascii=False)}\n'


if __name__ == '__main__':
    main()
